### ISSUE TITLE
Allow mailing list to depend on ref being updated

### ISSUE THREAD

**Issue by jsm28** [AdaCore/git-hooks#10]
Filing feature requests for GCC use of these hooks as issues here, as requested by Joel.

hooks.mailinglist, as noted in its documentation, only supports choosing lists to which to send commit emails based on the files changed in the commit. It would be useful for the script named to receive information about the ref being updated so it can choose based on that as well.

https://gcc.gnu.org/ml/gcc/2020-01/msg00311.html

**Comment by brobecke** [comment]
Implemented by the following commit:

| commit 4106237e9743d75976401e5b7cd6d13f00d8098f
| Author: Joel Brobecker <brobecker@adacore.com>
| Date:   Mon Jun 29 11:19:27 2020 -0700
| Subject: Add reference name as argument in call to hooks.mailinglist script
