### ISSUE TITLE
Add README for testsuite

### ISSUE THREAD

**Issue by simark** [AdaCore/git-hooks#15]
I'm noting here what it took to manage to successfully run the testsuite.  This should probably go in a README later.  Please correct me if anything is wrong.

* First, I really suggest using a virtualenv to avoid polluting the global installation: `virtualenv -p python2 env && source env/bin/activate`
* The `gnatpython` module is required.  I first tried to install the `python-gnatpython` from Ubuntu, but that didn't work: it doesn't like that `lib/testsuite.py` passes `discs=None` to `generate_run_testcase`.  I ended up installing [this](https://github.com/Nikokrock/gnatpython), which handles `discs == None` correctly.
* I ran `./run-testsuite`, everything failed.  I ran `./run-testsuite --diffs -v tests/KA13-007__rh_line_too_long`, and I was able to see some backtrace.  The `enum` module was missing.  I first did `pip install enum`, but that wasn't right.  I got another backtrace because the enums created using _that_ enum module are not iterable (which the code uses).  I installed `enum34` instead, and it was fine.

Almost everything passes.  The remaining failures are:

* `tests/LC27-012__logger_errors`: it looks like the test tries to use a mock syslog server that always fails, but I think that the test ends up using the real syslog server on my machine, so it fails to fail.
* `tests/LC27-002__nocvscheck_user_override`: I don't understand why

**Comment by brobecke** [comment]
Hi @simark . Well done for getting to that point!

For `tests/LC27-012__logger_errors`, you are correct. The override is supposed to occur via the use of an environment variable, which the testcase sets. It's weird that your logger would be called, given the logic for selecting which program we use is pretty simple.

For `tests/LC27-002__nocvscheck_user_override`, I wouldn't worry about it. This is a feature I had to implement at some point for legacy reasons which is no longer applicable.

If you want, you can consider the above to be good enough for testing purposes -- just remind me when you send patches to run them through the testsuite as well to completely validate them.

**Comment by simark** [comment]
Regarding:

> * The gnatpython module is required. I first tried to install the python-gnatpython from Ubuntu, but that didn't work: it doesn't like that lib/testsuite.py passes discs=None to generate_run_testcase. I ended up installing this, which handles discs == None correctly.

Is this repo what you use?  If not, where do you get your `gnatpython` package?

**Comment by brobecke** [comment]
I use a private version of gnatpython, which is private because it contains a lot of stuff which is really specific to AdaCore which we cannot share. We've since then started a transition away from gnatpython, towards a similar framework called "e3", with "e3-core" being the central repository (but you'll find other e3-xxx repositories as well).

For people outside AdaCore, the version you are using should be good for now.

For the future, I am planning on switching this testsuite to using pytest instead, so as to make it much easier for anyone outside AdaCore to run the testsuite as well.

**Comment by brobecke** [comment]
Hi @simark : The testsuite has now been transitioned to Python 3.x as well, and is based on pytest mostly. I've added a `README.md` file in the https://github.com/AdaCore/git-hooks/tree/master/testsuite directory as you suggested.

**Comment by simark** [comment]
Awesome, thanks!
