### ISSUE TITLE
Configuring when branch deletion is allowed

### ISSUE THREAD

**Issue by jsm28** [AdaCore/git-hooks#5]
Filing feature requests for GCC use of these hooks as issues here, as requested by Joel.

It would be useful to have a configuration option listing patterns for the names of refs for which branch deletion is allowed. (In GCC that would be only for refs starting refs/users/ or refs/vendors/.)

https://gcc.gnu.org/ml/gcc/2020-01/msg00135.html

**Comment by brobecke** [comment]
I implemented the following changes:

| commit c601254862121dec789d16a1c3c99f882f312b68
| Author: Joel Brobecker <brobecker@adacore.com>
| Date:   Mon Jun 29 11:10:57 2020 -0700
| Subject: add options to allow repositories to control branch deletion

And then, to give an option for projects to provide project-specific instructions on how to deal with the rejection, I added a second option.

| commit 453f2581f12014e3cf090c4027c2fc16d1b408a9
| Author: Joel Brobecker <brobecker@adacore.com>
| Date:   Mon Jun 29 11:14:14 2020 -0700
| Subject: Add support for hooks.rejected-branch-deletion-tip config option

For more info, see the hooks.allow-delete-branch and hooks.allow-delete-branch options in the documentation.
