### ISSUE TITLE
Update hook for custom checks

### ISSUE THREAD

**Issue by jsm28** [AdaCore/git-hooks#6]
Filing feature requests for GCC use of these hooks as issues here, as requested by Joel.

It would be useful to support a call out to an update-hook script to allow arbitrary custom checks to be made on whether a given ref update is permitted, without needing to patch them directly into the hooks.

https://gcc.gnu.org/ml/gcc/2020-01/msg00133.html

**Comment by brobecke** [comment]
This was implemented by the following commit:

commit 55be81f225db1e8ca5feef959002938d3acc3d8f
Author: Joel Brobecker <brobecker@adacore.com>
Date:   Sun Feb 23 15:24:54 2020 +0400

    Add support for hooks.update-hook configuration option
    
    This option allows users to specify a script to be run at update time,
    for each reference being updated. This script can then be used to perform
    additional checks on top of the standard checks already provided by
    our git-hooks.
