### ISSUE TITLE
Hooks to override default email subject and body

### ISSUE THREAD

**Issue by jsm28** [AdaCore/git-hooks#8]
Filing feature requests for GCC use of these hooks as issues here, as requested by Joel.

In GCC we have some customizations of how the commit hooks form the email subject and how they report the commit identifier in the message body. It would be useful for the hooks to have configuration options to call out to scripts that can customize these things without patching it into the hooks themselves.

https://gcc.gnu.org/ml/gcc/2020-01/msg00198.html

**Comment by brobecke** [comment]
This is now implemented by commit 2ebb722e13a82320c0296b451d8fcb426f44f0c0.

See the documentation on how to use this. There is also a script in  testsuite/tests/T209-006__commit_email_formatter called commit-email-formatter.py which you could look at, to see how it changes parts or all of the default commit email.
