### ISSUE TITLE
Only send commit emails for commits new to the repository

### ISSUE THREAD

**Issue by jsm28** [AdaCore/git-hooks#9]
Filing feature requests for GCC use of these hooks as issues here, as requested by Joel.

In GCC (and in glibc) we see the following pattern: there is a long-lived public development branch in the repository that gets updated from master every so often, either by a merge or by a rebase. When the merge or rebase occurs, the git hooks then send out an email for every commit that is new to that branch, including all those that were already on master and so had had an email sent out when they were first pushed to master.  The effect is that rather than each master commit getting emailed out once, it gets emailed out N+1 times eventually, where N is the number of active development branches that end up getting rebased or merged on top of that commit.

We'd like any given commit to get only a single email when first added to the repository, and not to get further emails when it's added to other branches by a merge or rebase. (A summary email for the push like https://sourceware.org/ml/glibc-cvs/2019-q4/msg00666.html is fine, though maybe it shouldn't give the full logs for the commits that were already in the repository, only their summaries. It's all the following emails for individual commits that were already in the repository that are the problem.)

https://gcc.gnu.org/ml/gcc/2020-01/msg00300.html

Note: if it's convenient for the "new to this repository" check to be "not reachable from any ref matching this set of patterns" rather than literally checking every ref in the repository, that would be fine and possibly more efficient, and there might be use cases for which checking a subset of refs is preferable.

https://gcc.gnu.org/ml/gcc/2020-01/msg00302.html

**Comment by iains** [comment]
" though maybe it shouldn't give the full logs for the commits that were already in the repository, only their summaries. "

That is probably essential - I ran into the issue mentioned here  [ https://gcc.gnu.org/ml/gcc-patches/2020-01/msg01004.html ] where the limit on the number of mergeemails was exceeded. 

I tested a squash merge commit (which does roughly the equivalent of listing every commit message for the squashed series) - and the combined commit message for 284 trunk commits was almost 400kb (which is heading for, or maybe exceeding, our ML message size limit).

So, it would be my suggestion that merges from master => devel / vendor / user branches should only get a single ML email, with the --oneline format for the entries that have been merged.  This is sufficient for finding stuff, and minimises redundant data.

**Comment by iains** [comment]
in fact, given that commit ranges are now per branch (yay!) .. it might even be enough to make the email simply give sha1..sha2.  The ancestors are discoverable by usual mechanisms (and visualised by UI or similar term tools).

**Comment by iains** [comment]
it's not clear if the case where a user or vendor** space branch is rebased is covered by this (i.e. do we consider those commits as 'really new'?).

Suppose I have 25+ Darwin branches on master (I do) which I rebase more-or-less daily
(I don't currently push these to the repo, but was hoping to be able to do so now we're git-based).
If every commit there is considered 'new' (which they will be in terms of SHA) that would represent more than 100 emails/day just from my user branches on master (and i have some on branches too).

Given that rebasing WIP is an important benefit of moving to Git, some strategy for handling this would be useful - either by rolling this into the 'new commit' concept or some alternate.

** It's not clear whether devel/ space branches would do this - but, of course, that is a tremendous advantage in keeping the new feature distinct from unrelated changes in the master.   The same issue would apply there too.

**Comment by brobecke** [comment]
Hi @jsm28 , does GCC have a defined process for people who are ready to submit the changes they have been developing in their own branches (vendor/user) back into master? What I'm wondering about is whether that user/vendor branch is expected to be merged, or whether the people working in the branch eventually split the changes they made into patches, and then submits them
as usual, eventually applying the approved patches as it if was a standard contribution (not coming
from a devel branch)?

**Comment by jsm28** [comment]
Changes are submitted the same way regardless of whether they were developed on a branch or not. Merge commits are not allowed on master, and thus all changes going onto master are new commits at the point where they go onto master.

**Comment by brobecke** [comment]
Thanks Joseph.

**Comment by Hi-Angel** [comment]
> If every commit there is considered 'new' (which they will be in terms of SHA) 

Just a nitpick to make sure there's no confusion: if you used `git rebase`, the SHA for "common" commits will be the same. It is an essential feature, so software like gitlab and github can create merge/pull requests where only the new commits are listed.

**Comment by brobecke** [comment]
Hi @jsm28, 

> Changes are submitted the same way regardless of whether they were developed on a branch or not. Merge commits are not allowed on master, and thus all changes going onto master are new commits at the point where they go onto master.

Just a note about what you are saying: If contributors develop a series of changes and push it to their user/vendor branch, and then rebase that branch on top of master before they contribute their changes to master, the commits on master will appear identical to those already on the user/vendor branch. I don't think you would want to silence those commits pushed to master, would you?

For me, what seems best is to silence the "official" commits (those pushed to the common development/release) branch when being pushed to the user/vendor branches, but keep the current email sending policy when on the official branches.

Would you confirm?

**Comment by jsm28** [comment]
It's certainly possible for someone to push first to their user/vendor branch then the same commit to master immediately thereafter, but I don't think that's the common case. It would be reasonable to mail separately for the commits going on master if desired in that case. This sounds like the "not reachable from any ref matching this set of patterns" possibility I mentioned in the original issue; if such a set of patterns is used, it could be set to match only certain official branches if mail is desired the first time a commit on a user/vendor branch is pushed to an official branch.

**Comment by brobecke** [comment]
> This sounds like the "not reachable from any ref matching this set of patterns" possibility I mentioned in the original issue; if such a set of patterns is used, it could be set to match only certain official branches if mail is desired the first time a commit on a user/vendor branch is pushed to an official branch.

I think we're on the same wavelength. Thanks Joseph.

**Comment by brobecke** [comment]
Commit a62e4bcad0b4ab563b662e5facba8602b1b3079f adds a new configuration option:

* **`hooks.email-new-commits-only`** [list]:

  A list of regular expressions matching some reference names for which
  commit emails should only be sent for the commits that are new to
  the entire repository (as opposed to just being new to the branch
  being updated). In other words, if performing an update to a reference
  matching this config option, commits found in another pre-existing
  reference will not trigger a commit email.
